# Generated by Django 5.2.8 on 2025-11-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'رسالة', 'verbose_name_plural': 'الرسائل'},
        ),
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'ordering': ['-updated_at'], 'verbose_name': 'إعداد الموقع', 'verbose_name_plural': 'إعدادات الموقع'},
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='address',
            field=models.CharField(blank=True, help_text='عنوان المتجر أو مقر الإدارة.', max_length=255, null=True, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تعديل'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(help_text='أدخل بريدك الإلكتروني للرد على استفسارك.', max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(help_text='اكتب تفاصيل رسالتك أو استفسارك.', verbose_name='الرسالة'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(help_text='أدخل اسمك الكامل.', max_length=100, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, help_text='موضوع الرسالة (اختياري).', max_length=150, null=True, verbose_name='الموضوع'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='البريد الإلكتروني الرسمي للتواصل.', max_length=254, null=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='رقم الهاتف أو الواتساب الخاص بالمتجر.', max_length=20, null=True, verbose_name='رقم التواصل'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='footer_text',
            field=models.CharField(blank=True, help_text='نص يظهر أسفل الموقع، مثل حقوق النشر أو رسالة قصيرة.', max_length=255, null=True, verbose_name='نص التذييل'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, help_text='يمكنك رفع الشعار الرسمي للمتجر.', null=True, upload_to='logos/', verbose_name='شعار الموقع'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(default='متجري الإلكتروني', help_text='اسم المتجر الذي سيظهر في الترويسة والتذييل.', max_length=100, verbose_name='اسم الموقع'),
        ),
    ]
